args<-commandArgs(trailingOnly=TRUE)
script_arg<-grep('^--file=',commandArgs(trailingOnly=FALSE),value=TRUE)[1]
module_dir<-normalizePath(file.path(dirname(sub('^--file=','',script_arg)),'..'),mustWork=FALSE)
root_arg<-if(length(args))args[1] else Sys.getenv('HCC_OS_DISCOVERY_ROOT')
if(!nzchar(root_arg))stop('Provide the archived discovery-analysis root as argument 1 or HCC_OS_DISCOVERY_ROOT.')
root<-normalizePath(root_arg,mustWork=TRUE)
out<-normalizePath(if(length(args)>1)args[2] else module_dir,mustWork=FALSE)
dir.create(file.path(out,'data/raw'),recursive=TRUE,showWarnings=FALSE)
dir.create(file.path(out,'logs'),recursive=TRUE,showWarnings=FALSE)
wr<-function(x,f)write.csv(x,file.path(out,'data/raw',f),row.names=FALSE)
e<-new.env();load(file.path(root,'QWEN0208_no_GSE14520.Rdata'),envir=e)
writeLines(e$g,file.path(out,'data/raw/candidate_448_genes.txt'))
for(co in names(e$list_train_vali_Data))wr(e$list_train_vali_Data[[co]],paste0(co,'_legacy_cleaned_candidates.csv'))
r<-readRDS(file.path(out,'data/raw/frozen_risks.rds'))
for(co in names(r))wr(r[[co]],paste0(co,'_frozen_risks.csv'))
z<-new.env();load(file.path(root,'临床治疗/exp1_surv1.Rdata'),envir=z)
wr(z$surv1,'TCGA_clinical_source.csv')
wr(data.frame(ID=colnames(z$exp1),t(z$exp1[e$g,,drop=FALSE]),check.names=FALSE),'TCGA_unclipped_448_expression.csv')
con<-gzfile(file.path(out,'data/raw/TCGA_full_expression_logscale.csv.gz'),'w')
write.csv(data.frame(gene=rownames(z$exp1),z$exp1,check.names=FALSE),con,row.names=FALSE);close(con)
m<-new.env();load(file.path(root,'StepCox_GBM_model_object.Rdata'),envir=m)
writeLines(m$gbm_model$selected_genes,file.path(out,'data/raw/frozen_128_genes.txt'))
wr(m$gbm_model$variable_importance,'frozen_variable_importance.csv')
sink(file.path(out,'logs/frozen_model_details.txt'))
str(m$gbm_model$gbm_fit,max.level=1,list.len=40)
cat('training cutoff:',median(r[['TCGA-LIHC']]$RS),'\n')
cat('unique patients:',length(unique(substr(r[['TCGA-LIHC']]$ID,1,12))),'\n')
for(co in names(e$list_train_vali_Data)){dat<-e$list_train_vali_Data[[co]];cat(co,nrow(dat),'patients',sum(dat[,3]),'events\n');print(head(dat[,1:6]));print(quantile(as.matrix(dat[,-(1:3)])))}
sink()
